export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const shopping = {
  ADD_TO_CART: 'ADD_TO_CART',
  CHECKOUT_REQUEST: 'CHECKOUT_REQUEST',
  CHECKOUT_SUCCESS: 'CHECKOUT_SUCCESS',
  CHECKOUT_FAILURE: 'CHECKOUT_FAILURE',
  RECEIVE_PRODUCTS: 'RECEIVE_PRODUCTS',
};

export const RECEIVE_STORIES = 'RECEIVE_STORIES';
